#!/bin/sh

set -e

# We need to use --no-options so that a gpg.conf from an older version
# of gpg is not used.
GPG="../../g10/gpg --no-options --batch --quiet
     --no-secmem-warning --allow-secret-key-import"

NAMES='Alpha Bravo Charlie Delta Echo Foxtrot Golf Hotel India
       Juliet Kilo Lima Mike November Oscar Papa Quebec Romeo
       Sierra Tango Uniform Victor Whisky XRay Yankee Zulu'

if [ "$1" = "--clean" ]; then
    (for i in $NAMES; do
	[ -d $i ] && rm -r $i
    done) || true
    exit 0
fi

$GPG --dearmor -o secdemo.pgp --yes ../checks/secdemo.asc
$GPG --dearmor -o pubdemo.pgp --yes ../checks/pubdemo.asc
[ -f ./tdb.tmp ] && rm ./tdb.tmp
GPGDEMO="$GPG --homedir . --trustdb-name ./tdb.tmp --no-default-keyring
	 --keyring pubdemo.pgp --secret-keyring secdemo.pgp"
echo -n "Creating:"
for name in $NAMES; do
    echo -n " $name"
    [ -d $name ] && rm -r $name
    mkdir $name
    $GPGDEMO --export-secret-key -o - $name > $name/Secret.pgp
    $GPG --homedir $name --import $name/Secret.pgp
    $GPGDEMO --export -o - $name > $name/Public.pgp
    $GPG --homedir $name --import $name/Public.pgp
    [ -f $name/pubring.gpg~ ] && rm $name/pubring.gpg~
done
echo "."
[ -f ./tdb.tmp ] && rm ./tdb.tmp
rm pubdemo.pgp secdemo.pgp


